# Generated by Django 3.2.4 on 2021-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='/media/avatars/avatar.png', max_length=500, null=True, verbose_name='头像'),
        ),
    ]
