# Generated by Django 3.2.4 on 2021-07-03 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('state', models.BooleanField(default=True, verbose_name='删除')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='文件')),
                ('type', models.CharField(blank=True, max_length=512, null=True, verbose_name='文件后缀')),
                ('filename', models.CharField(blank=True, max_length=512, null=True, verbose_name='文件名称')),
                ('filetype', models.CharField(blank=True, max_length=512, null=True, verbose_name='文件类型')),
                ('filesize', models.CharField(blank=True, max_length=512, null=True, verbose_name='文件大小')),
                ('filepath', models.CharField(blank=True, max_length=512, null=True, verbose_name='文件路径')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'db_table': 'upload',
            },
        ),
    ]
